# Generated by Django 5.2.17 on 2026-09-18 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('people', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('difficulty', models.CharField(choices=[('easy', 'Easy'), ('hard', 'Hard'), ('extreme', 'Extreme'), ('kek', 'Kek')], default='easy', max_length=20)),
                ('budget', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('planned', 'Planned'), ('in_progress', 'In Progress'), ('completed', 'Completed')], default='planned', max_length=20)),
                ('start_date', models.DateField()),
                ('assigned_people', models.ManyToManyField(blank=True, related_name='projects', to='people.people')),
            ],
        ),
    ]
