# Generated by Django 5.2.17 on 2026-09-12 18:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('qualifications', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='People',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('age', models.IntegerField(validators=[django.core.validators.MinValueValidator(18, message='You must be over 18')])),
                ('job_description', models.CharField(max_length=200)),
                ('qualifications', models.ManyToManyField(blank=True, related_name='people', to='qualifications.qualifications')),
            ],
        ),
    ]
