# Generated by Django 5.2.17 on 2026-09-12 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Qualifications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('university', models.CharField(max_length=200)),
                ('courses', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
    ]
