# Generated by Django 5.2.17 on 2026-09-17 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qualifications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='qualifications',
            name='slug',
            field=models.SlugField(blank=True, max_length=200, unique=True),
        ),
    ]
